### ISSUE TITLE
Request: Ability to set dropper to drop a specified number of an item instead of just one item

### ISSUE THREAD

**Issue by AmyMoriyama** [loosewheel/lwcomponents#1]
Request: Ability to set dropper to drop a specified number of an item instead of just one item.

One use case scenario:
Chest full of food that is filled from automatic farms. Hungry player comes along, presses a button, out comes 20 of some food, or 30, or 10, or whatever is set in the dropper.

**Comment by loosewheel** [comment]
Added quantity field to droppers and updated digilines messages to accommodate a quantity. Present implementations should still work the same. Already existing droppers are updated when the form is accessed.

If multiple items are in a dropper each item is treated individually. An action will not drop multiple items to fulfil the quantity. See the docs for more.

Note it may take a day for this change to come through on ContentDB.
