### ISSUE TITLE
Request: crafting grid and guide that can take from storage units

### ISSUE THREAD

**Issue by AmyMoriyama** [loosewheel/lwcomponents#3]
Request: crafting grid that can take from storage units added to the storage indexer.

The idea, be able to open the storage indexer, look up a recipe via the guide, then craft it using items automatically taken from the storage units.

The crafting guide used by unified inventory is almost perfect for such a thing (the way it functions). Or, maybe create a new thing just for that. Maybe a "crafting station".

**Comment by loosewheel** [comment]
Added crafters. These are additional nodes which have other uses, but attached to storage units perform this function. There is no  crafting guide, but the list of craftable items are only those possible from the input items.

**Comment by loosewheel** [comment]
Updated UI so when an item in the list is clicked, if that item has more than 1 recipe satisfied by the available items, the grafting grid is replaced with the recipes found for the item. Walk through and click Craft to use that recipe.
